<?php

namespace AppBundle\Repository;

/**
 * TaldeaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaldeaRepository extends \Doctrine\ORM\EntityRepository
{
}
