imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        gelf:
            type: gelf
            publisher:
                hostname: 172.28.64.136
                port: 12201
            level: debug
            formatter: app.gelf_formatter
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: "!event"
            max_files: 7
        console:
            type: console
