
imports:
    - { resource: legacy_aliases.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false


    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    AppBundle\Service\DirectoryNamer:
        public: true
        class: AppBundle\Service\DirectoryNamer
        arguments: ['%kernel.root_dir%']

    AppBundle\Service\NotificationService:
        public: true
        class: AppBundle\Service\NotificationService

    AppBundle\Service\CalendarService:
        public: true
        class: AppBundle\Service\CalendarService

    Symfony\Component\Ldap\Ldap:
        arguments: ['@Symfony\Component\Ldap\Adapter\ExtLdap\Adapter']

    Symfony\Component\Ldap\Adapter\ExtLdap\Adapter:
        arguments:
            -   host: pasaia.net
                port: 389
                #encryption: tls
                options:
                    protocol_version: 3
                    referrals: false

    AppBundle\Service\LdapService:
        public: true
        class: AppBundle\Service\LdapService
        arguments:
            - '%ldap_server%'
            - '%ldap_username%'
            - '%ldap_base_dn%'
            - '%ldap_password%'
