
imports:
    - { resource: legacy_aliases.yml }

parameters:
    fr3d_ldap.security.authentication.provider.class: AppBundle\Security\Authentication\LdapAuthenticationProvider

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false


    AppBundle\:
        resource: '../../src/AppBundle/*'
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    fr3d_ldap.security.authentication.provider:
        class: "%fr3d_ldap.security.authentication.provider.class%"
#        arguments:
#            - '@security.user_checker'
#            - $providerKey: ''
#            - ''
#            - '@fr3d_ldap.ldap_manager'
#            - '@fos_user.user_manager'
#            - "%security.authentication.hide_user_not_found%"
#            - "@doctrine.orm.entity_manager"
#            - "@app.ldap.service"
#            - '@logger'

    AppBundle\Ldap\UserHydrator:
        public: true
        autowire: true
        class: AppBundle\Ldap\UserHydrator

    AppBundle\Service\DirectoryNamer:
        public: true
        class: AppBundle\Service\DirectoryNamer
        arguments: ['%kernel.root_dir%']

    AppBundle\Service\NotificationService:
        public: true
        class: AppBundle\Service\NotificationService

    AppBundle\Service\CalendarService:
        public: true
        class: AppBundle\Service\CalendarService

#    AppBundle\Repository\EskaeraRepository:
#        public: true
#        class: AppBundle\Repository\EskaeraRepository
#        factory: ["@doctrine", "getRepository"]
#        arguments: ['AppBundle:Eskaera']
#        calls:
#            - ["setLizentziaType", ["%type_lizentzia%"]]

    AppBundle\Service\LdapService:
        public: true
        class: AppBundle\Service\LdapService
        arguments:
            - '%ldap_server%'
            - '%ldap_username%'
            - '%ldap_base_dn%'
            - '%ldap_password%'
