
parameters:
    fr3d_ldap.security.authentication.provider.class: AppBundle\Security\Authentication\LdapAuthenticationProvider

services:
  fr3d_ldap.security.authentication.provider:
      class: "%fr3d_ldap.security.authentication.provider.class%"
      arguments:
          - '@security.user_checker'
          - ''
          - ''
          - '@fr3d_ldap.ldap_manager'
          - '@fos_user.user_manager'
          - "%security.authentication.hide_user_not_found%"
  app.ldap.user_hydrator:
      class: AppBundle\Ldap\UserHydrator

  app.menu_builder:
      class: AppBundle\Menu\Builder
      arguments: ["@service_container"]

  app.main_menu:
      class: Knp\Menu\MenuItem # the service definition requires setting the class
      factory: ["@app.menu_builder", createMainMenu]
      arguments: ["@request_stack"]
      tags:
          - { name: knp_menu.menu, alias: main } # The alias is what is used to retrieve the menu

  app.document.directory_namer:
      class: AppBundle\Service\DirectoryNamer
      arguments: [%kernel.root_dir%]

  app.sinatzeke:
        class: AppBundle\Service\NotificationService
#        arguments: ["@doctrine.orm.entity_manager"]
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage"]

