---

# Regular Symfony installation steps

- name: Install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: Install vendors
  composer: command=install working_dir={{ symfony_path }} no_dev={{ (symfony_deploy_env == "prod") | ternary('yes', 'no') }} arguments="--no-interaction"
  environment:
    SYMFONY_ENV: "{{ symfony_deploy_env }}"

- stat:
    path: "{{ ansistrano_deploy_to }}/shared/{{ shared_path_parameters }}"
  register: parameters_file

- name: Create shared parameters.yml
  shell: "cp {{ ansistrano_release_path.stdout }}/{{ shared_path_parameters }} {{ ansistrano_deploy_to }}/shared/{{ shared_path_parameters }}"
  when: not parameters_file.stat.exists

# Any specific installation steps

- name: Install vendors
  composer: command=install working_dir={{ symfony_path }} arguments="--no-interaction"



- name: npm install/update
  shell: /usr/bin/zsh -lc "/root/.nvm/versions/node/v6.10.1/bin/npm install"
  tags: npm
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"

#- name: Install packages based on package.json.
#  command: "/opt/npm/bin/gulp"
#  tags: npm