---

- name: Install packages based on package.json.
  npm:
    path: "{{ ansistrano_release_path.stdout }}"
#    executable: /root/.nvm/versions/node/v6.10.1/bin/npm
    executable: /usr/bin/npm
    state: present

- name: Run gulp
  command: /usr/bin/gulp dev
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"

- name: Run sass
  command: /usr/bin/gulp sass:prod
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"

- name: Install CKEditor.
  npm:
    path: "{{ ansistrano_release_path.stdout }}"
    executable: php bin/console ckeditor:install --tag=4.22.1 --clear=drop
    state: present

- name: Install CKEditor and all assets
  npm:
    path: "{{ ansistrano_release_path.stdout }}"
    executable: php bin/console assets:install
    state: present
