---

- name: Install packages based on package.json.
  npm:
    path: "{{ ansistrano_release_path.stdout }}"
#    executable: /root/.nvm/versions/node/v6.10.1/bin/npm
    executable: /usr/bin/npm
    state: present

- name: Run gulp
#  command: /root/.nvm/versions/node/v6.10.1/bin/gulp prod
  command: /usr/bin/gulp prod
  args:
    chdir: "{{ ansistrano_release_path.stdout }}"

- name: Run ckeditor install
    #  command: /root/.nvm/versions/node/v6.10.1/bin/gulp prod
  command: php bin/console ckedit:install
  args:
      chdir: "{{ ansistrano_release_path.stdout }}"
